
name: raycast

dependencies:
- base
- mtl
- transformers
- gloss-raster
- gloss
- exceptions
- vector

default-extensions:
- BlockArguments
- DerivingStrategies
- ImportQualifiedPost

ghc-options: -O3 -fexpose-all-unfoldings

library:
  source-dirs:
  - src

executables:
  raycast-test:
    source-dirs:
    - app

    main: Main.hs

    dependencies:
    - raycast
